import { TerminalSessionInfo, CommandState, CommandFinishResult, TerminalExecResult } from '../../shared/types/terminal';
export declare class TerminalService {
    private session;
    private ptyProcess;
    private disposed;
    private commandState;
    private shellIntegrationEnabled;
    private shellIntegrationReady;
    private outputBuffer;
    private readonly MAX_BUFFER_LINES;
    private readonly MAX_COMMAND_OUTPUT;
    private commandFinishResolvers;
    private shellReadyResolvers;
    private commandExecutionChain;
    private lastCommandDispatchAt;
    getSession(): TerminalSessionInfo | null;
    init(): void;
    startSession(cols?: number, rows?: number): TerminalSessionInfo;
    write(data: string): void;
    dispatchCommand(command: string): void;
    getRecentOutput(lineCount?: number): string;
    getCommandState(): CommandState;
    getCwd(): string;
    isBusy(graceMs?: number): boolean;
    waitForCommandFinish(timeoutMs?: number): Promise<CommandFinishResult | null>;
    waitForShellReady(timeoutMs?: number): Promise<boolean>;
    executeCommand(command: string, timeoutMs?: number): Promise<CommandFinishResult | null>;
    executeCommandIsolated(command: string, options?: {
        cwd?: string;
        timeoutMs?: number;
    }): Promise<TerminalExecResult>;
    resize(cols: number, rows: number): void;
    restart(): TerminalSessionInfo;
    setAppQuitting(): void;
    dispose(): void;
    persistNow(): void;
    private wirePtyEvents;
    private resolveCommandCwd;
    private cleanupPty;
    private enqueueExclusiveCommand;
    private updateState;
    private mapToSurfaceStatus;
    private emitStatus;
    private emitLog;
    private handleOscEvent;
    private resolveCommandFinish;
    private resolveShellReady;
}
export declare const terminalService: TerminalService;
