import { AgentInvocationOptions, InvocationResult, ProviderRuntime } from '../../shared/types/model';
export declare class AgentModelService {
    private providers;
    private activeTaskProviders;
    private sharedPrimaryAppServerProvider;
    init(): void;
    dispose(): Promise<void>;
    getProviderStatuses(): Record<string, ProviderRuntime>;
    resolve(prompt: string, explicitOwner?: string, options?: AgentInvocationOptions): string;
    cancel(taskId: string): boolean;
    getTaskMemory(taskId: string): import("../../shared/types/model").TaskMemoryRecord;
    invoke(taskId: string, prompt: string, explicitOwner?: string, options?: AgentInvocationOptions): Promise<InvocationResult>;
    private initializeCodexProvider;
    private initializeAppServerProvider;
    private initializeHaikuProvider;
    private pickProvider;
    private pickAutoProvider;
    private createPreferredSubAgentProvider;
    private createProviderInstance;
    private createTaskInvocation;
    private disposeTaskInvocation;
    private buildUnavailableProviderMessage;
    private assertProviderSupportsPrompt;
    private getProviderRoutingCapabilities;
    private setRuntime;
    private log;
    private emitProgress;
    private emitStartupStatuses;
    private queueBackgroundResearchSynthesis;
    private runBackgroundResearchSynthesis;
}
export declare const agentModelService: AgentModelService;
