import type { AgentToolName } from './AgentTypes';
import type { AgentTaskKind, AgentTaskProfileOverride } from '../../shared/types/model';
export type AgentTaskProfile = {
    kind: AgentTaskKind;
    skillNames: string[];
    allowedTools: 'all' | AgentToolName[];
    canSpawnSubagents: boolean;
    maxToolTurns: number;
    requiresBrowserSearchDirective: boolean;
};
export declare function buildTaskProfile(prompt: string, overrides?: AgentTaskProfileOverride): AgentTaskProfile;
export declare function withBrowserSearchDirective(prompt: string, overrides?: AgentTaskProfileOverride): string;
export declare function looksLikeOrchestrationTask(prompt: string): boolean;
export declare function looksLikeImplementationTask(prompt: string): boolean;
export declare function looksLikeResearchTask(prompt: string): boolean;
export declare function looksLikeBrowserAutomationTask(prompt: string): boolean;
export declare function looksLikeReviewTask(prompt: string): boolean;
export declare function looksLikeDebugTask(prompt: string): boolean;
export declare const looksLikeDelegationTask: typeof looksLikeOrchestrationTask;
export declare const looksLikeBrowserSearchTask: typeof looksLikeResearchTask;
export declare const looksLikeBrowserAutomationWork: typeof looksLikeBrowserAutomationTask;
export declare const looksLikeLocalCodeTask: typeof looksLikeImplementationTask;
