import type { Session, WebContents } from 'electron';
import { BrowserConsoleEvent, BrowserNetworkEvent } from '../../shared/types/browserIntelligence';
import type { BrowserNetworkInterceptionPolicy, BrowserOperationNetworkCapture, BrowserOperationNetworkScope } from './browserNetworkSupport';
export declare class BrowserInstrumentation {
    private readonly contextId;
    private tabIdByWebContentsId;
    private consoleEventsByTab;
    private networkEventsByTab;
    private requestMetadataById;
    private requestIdsByTab;
    private operationScopesById;
    private interceptionPolicies;
    private sessionAttached;
    private callbackReturn;
    constructor(contextId: string);
    attachSession(sessionInstance: Session): void;
    registerNetworkInterceptionPolicy(policy: BrowserNetworkInterceptionPolicy): void;
    beginOperationNetworkScope(scope: BrowserOperationNetworkScope): void;
    completeOperationNetworkScope(operationId: string): BrowserOperationNetworkCapture | null;
    attachTab(tabId: string, webContents: WebContents): void;
    detachTab(tabId: string, webContentsId: number): void;
    getConsoleEvents(tabId?: string, since?: number): BrowserConsoleEvent[];
    getNetworkEvents(tabId?: string, since?: number): BrowserNetworkEvent[];
    private pushConsoleEvent;
    private pushNetworkEvent;
    private requestKeyFromDetails;
    private resolveTabId;
    private resolveOperationId;
    private recordOperationEvent;
    private buildInterceptionContext;
    private applyBeforeRequestPolicies;
    private applyBeforeSendHeadersPolicies;
    private applyHeadersReceivedPolicies;
}
