import { BrowserHistoryEntry, BookmarkEntry, BrowserSettings } from '../../shared/types/browser';
export declare function loadBrowserHistory(): BrowserHistoryEntry[];
export declare function loadLastUrls(): string[];
export declare function loadActiveTabIndex(): number;
export declare function saveBrowserHistory(history: BrowserHistoryEntry[], lastUrls: string[], activeTabIndex: number): void;
export declare function loadBookmarks(): BookmarkEntry[];
export declare function saveBookmarks(bookmarks: BookmarkEntry[]): void;
export declare function loadSettings(): BrowserSettings;
export declare function saveSettings(settings: BrowserSettings): void;
export declare function flushAll(): void;
