export declare const ARTIFACT_FORMATS: readonly ["md", "txt", "html", "csv"];
export type ArtifactFormat = typeof ARTIFACT_FORMATS[number];
export declare const ARTIFACT_STATUSES: readonly ["created", "active", "updating", "failed", "archived"];
export type ArtifactStatus = typeof ARTIFACT_STATUSES[number];
export type ArtifactActor = 'user' | 'system' | string;
export type ArtifactRecord = {
    id: string;
    title: string;
    format: ArtifactFormat;
    workingPath: string;
    sourcePath?: string;
    createdBy: ArtifactActor;
    lastUpdatedBy: ArtifactActor;
    createdAt: number;
    updatedAt: number;
    status: ArtifactStatus;
    linkedTaskIds: string[];
    previewable: boolean;
    exportable: boolean;
    archived: boolean;
};
export type CreateArtifactInput = {
    title: string;
    format: ArtifactFormat;
    sourcePath?: string;
    createdBy: ArtifactActor;
    taskId?: string;
};
export type ArtifactMetadataPatch = Partial<Pick<ArtifactRecord, 'title' | 'sourcePath' | 'lastUpdatedBy' | 'status' | 'previewable' | 'exportable' | 'archived'>>;
export declare function isArtifactFormat(value: string): value is ArtifactFormat;
export declare function isArtifactStatus(value: string): value is ArtifactStatus;
