"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppEventType = void 0;
var AppEventType;
(function (AppEventType) {
    AppEventType["TASK_CREATED"] = "TASK_CREATED";
    AppEventType["TASK_UPDATED"] = "TASK_UPDATED";
    AppEventType["TASK_COMPLETED"] = "TASK_COMPLETED";
    AppEventType["LOG_ADDED"] = "LOG_ADDED";
    AppEventType["WINDOW_BOUNDS_CHANGED"] = "WINDOW_BOUNDS_CHANGED";
    AppEventType["WINDOW_FOCUSED"] = "WINDOW_FOCUSED";
    // Execution split events (replaces old layout presets)
    AppEventType["EXECUTION_SPLIT_CHANGED"] = "EXECUTION_SPLIT_CHANGED";
    AppEventType["EXECUTION_LAYOUT_APPLIED"] = "EXECUTION_LAYOUT_APPLIED";
    // Surface action lifecycle events
    AppEventType["SURFACE_ACTION_SUBMITTED"] = "SURFACE_ACTION_SUBMITTED";
    AppEventType["SURFACE_ACTION_STARTED"] = "SURFACE_ACTION_STARTED";
    AppEventType["SURFACE_ACTION_COMPLETED"] = "SURFACE_ACTION_COMPLETED";
    AppEventType["SURFACE_ACTION_FAILED"] = "SURFACE_ACTION_FAILED";
    AppEventType["SURFACE_ACTION_RESULT_UPDATED"] = "SURFACE_ACTION_RESULT_UPDATED";
    AppEventType["APP_STATE_SYNCED"] = "APP_STATE_SYNCED";
    // Browser runtime lifecycle events
    AppEventType["BROWSER_SURFACE_CREATED"] = "BROWSER_SURFACE_CREATED";
    AppEventType["BROWSER_NAVIGATION_STARTED"] = "BROWSER_NAVIGATION_STARTED";
    AppEventType["BROWSER_NAVIGATION_UPDATED"] = "BROWSER_NAVIGATION_UPDATED";
    AppEventType["BROWSER_NAVIGATION_COMPLETED"] = "BROWSER_NAVIGATION_COMPLETED";
    AppEventType["BROWSER_NAVIGATION_FAILED"] = "BROWSER_NAVIGATION_FAILED";
    AppEventType["BROWSER_TITLE_UPDATED"] = "BROWSER_TITLE_UPDATED";
    AppEventType["BROWSER_HISTORY_UPDATED"] = "BROWSER_HISTORY_UPDATED";
    AppEventType["BROWSER_DOWNLOAD_STARTED"] = "BROWSER_DOWNLOAD_STARTED";
    AppEventType["BROWSER_DOWNLOAD_UPDATED"] = "BROWSER_DOWNLOAD_UPDATED";
    AppEventType["BROWSER_DOWNLOAD_COMPLETED"] = "BROWSER_DOWNLOAD_COMPLETED";
    AppEventType["BROWSER_PERMISSION_REQUESTED"] = "BROWSER_PERMISSION_REQUESTED";
    AppEventType["BROWSER_PERMISSION_RESOLVED"] = "BROWSER_PERMISSION_RESOLVED";
    AppEventType["BROWSER_STATUS_UPDATED"] = "BROWSER_STATUS_UPDATED";
    AppEventType["BROWSER_STATE_CHANGED"] = "BROWSER_STATE_CHANGED";
    // Tab lifecycle events
    AppEventType["BROWSER_TAB_CREATED"] = "BROWSER_TAB_CREATED";
    AppEventType["BROWSER_TAB_CLOSED"] = "BROWSER_TAB_CLOSED";
    AppEventType["BROWSER_TAB_ACTIVATED"] = "BROWSER_TAB_ACTIVATED";
    AppEventType["BROWSER_TAB_UPDATED"] = "BROWSER_TAB_UPDATED";
    // Bookmark events
    AppEventType["BROWSER_BOOKMARK_ADDED"] = "BROWSER_BOOKMARK_ADDED";
    AppEventType["BROWSER_BOOKMARK_REMOVED"] = "BROWSER_BOOKMARK_REMOVED";
    // Extension events
    AppEventType["BROWSER_EXTENSION_LOADED"] = "BROWSER_EXTENSION_LOADED";
    AppEventType["BROWSER_EXTENSION_REMOVED"] = "BROWSER_EXTENSION_REMOVED";
    // Model lifecycle events
    AppEventType["MODEL_PROVIDER_DETECTED"] = "MODEL_PROVIDER_DETECTED";
    AppEventType["MODEL_PROVIDER_STATUS_CHANGED"] = "MODEL_PROVIDER_STATUS_CHANGED";
    AppEventType["MODEL_INVOCATION_STARTED"] = "MODEL_INVOCATION_STARTED";
    AppEventType["MODEL_INVOCATION_PROGRESS"] = "MODEL_INVOCATION_PROGRESS";
    AppEventType["MODEL_INVOCATION_COMPLETED"] = "MODEL_INVOCATION_COMPLETED";
    AppEventType["MODEL_INVOCATION_FAILED"] = "MODEL_INVOCATION_FAILED";
    // Terminal session lifecycle events
    AppEventType["TERMINAL_SESSION_CREATED"] = "TERMINAL_SESSION_CREATED";
    AppEventType["TERMINAL_SESSION_STARTED"] = "TERMINAL_SESSION_STARTED";
    AppEventType["TERMINAL_SESSION_OUTPUT"] = "TERMINAL_SESSION_OUTPUT";
    AppEventType["TERMINAL_SESSION_RESIZED"] = "TERMINAL_SESSION_RESIZED";
    AppEventType["TERMINAL_SESSION_EXITED"] = "TERMINAL_SESSION_EXITED";
    AppEventType["TERMINAL_SESSION_ERROR"] = "TERMINAL_SESSION_ERROR";
    AppEventType["TERMINAL_SESSION_RESTARTED"] = "TERMINAL_SESSION_RESTARTED";
    AppEventType["TERMINAL_STATUS_UPDATED"] = "TERMINAL_STATUS_UPDATED";
    AppEventType["TERMINAL_SESSION_REATTACHED"] = "TERMINAL_SESSION_REATTACHED";
    AppEventType["TERMINAL_COMMAND_FINISHED"] = "TERMINAL_COMMAND_FINISHED";
})(AppEventType || (exports.AppEventType = AppEventType = {}));
//# sourceMappingURL=events.js.map